const APPENDIX = '_PT';
export const GET_PARTS = 'GET_PARTS'+APPENDIX;
export const SET_PARTS = 'SET_PARTS'+APPENDIX;
export const SET_ACTIVE_POSITION = 'SET_ACTIVE_POSITION'+APPENDIX;
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'+APPENDIX;